# Generated by Django 4.1.1 on 2022-09-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_alter_restaurantmodel_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='restaurantmodel',
            name='administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
