# Generated by Django 4.1.1 on 2022-09-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_remove_restaurantmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='restaurant', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
