# Generated by Django 4.1.1 on 2022-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_menudishassociatemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishmodel',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='dishmodel',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
