# Generated by Django 4.1.1 on 2022-09-25 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0007_votemodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votemodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='votemodel',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='votemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='dishes',
            field=models.ManyToManyField(related_name='menus', to='restaurants.dishmodel'),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='votes',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MenuDishAssociateModel',
        ),
        migrations.DeleteModel(
            name='VoteModel',
        ),
    ]
