# Generated by Django 4.1.1 on 2022-09-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_votemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='dishes',
        ),
    ]
