# Generated by Django 4.1.1 on 2022-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_menumodel_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='dishes',
            field=models.ManyToManyField(related_name='menus', to='restaurants.dishmodel'),
        ),
    ]
