# Generated by Django 4.1.1 on 2022-09-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.SmallIntegerField(choices=[('1', 'admin'), ('2', 'restaurant_admin'), ('3', 'employee')], default='3'),
        ),
    ]
