# Generated by Django 4.1.1 on 2022-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customusermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('ad', 'admin'), ('ra', 'restaurant_admin'), ('em', 'employee')], default='em', max_length=2),
        ),
    ]
